import * as THREE from "three";

globalThis.THREE = THREE;
window.dispatchEvent(new Event("three-ready"));

import "./config/constants.js";
import "./audio/audio.js";
import "./i18n/translations.js";
import "./i18n/menu-translations.js";
import "./i18n/i18n.js";
import "./data/city-data.js";
import "./data/progression-data.js";
import "./data/world-data.js";
import "./state/factories.js";
import "./ui/icons.js";
import "./ui/app-view.js";
import "./ui/shell.js";
import "./ui/world-view.js";
import "./ui/city-3d-assets.js";
import "./ui/city-scene-3d.js";
import "./ui/city-view.js";
import "./ui/hex-inspector.js";
import "./ui/drawers.js";
import "./ui/components.js";
import "./ui/menu-view.js";
import "./selectors.js";
import "./ui/encyclopedia-view.js";
import "./ui/onboarding-flow.js";
import "./actions/city-actions.js";
import "./actions/diplomacy-actions.js";
import "./actions/unit-actions.js";
import "./actions/navigation-actions.js";
import "./systems/social.js";
import "./systems/turn-events.js";
import "./systems/city-economy.js";
import "./systems/scout-worker.js";
import "./systems/hostiles.js";
import "./utils/log.js";
import "./utils/math.js";
import "./systems/combat-resolve.js";
import "./systems/run-goal.js";
import "./world/generation.js";
import "./world/glyphs.js";
import "./systems/army-field.js";
import "./world/map-queries.js";
import "./systems/pulse-and-summary.js";
import "./systems/turn.js";
import "./input/keyboard.js";
